github_url: https://github.com/Polidea/RxBluetoothKit
module: RxBluetoothKit
author_url: https://polidea.com
author: Polidea
author_name: Polidea
swift_version: 3.0
clean: true
output: Documentation

podspec: RxBluetoothKit.podspec
